import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-container-high": "#ebe7e7",
        "error": "#ba1a1a",
        "surface-dim": "#dcd9d9",
        "inverse-surface": "#313030",
        "on-primary-fixed": "#001550",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b6c4ff",
        "on-tertiary-container": "#ceecff",
        "on-background": "#1c1b1b",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-fixed-variant": "#003ab2",
        "on-surface": "#1c1b1b",
        "on-secondary-fixed": "#1b1c1c",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary": "#5f5e5e",
        "on-tertiary-fixed-variant": "#004d67",
        "on-tertiary-fixed": "#001e2b",
        "surface-container-highest": "#e5e2e1",
        "on-primary-container": "#e4e7ff",
        "outline": "#737688",
        "on-surface-variant": "#434656",
        "tertiary": "#005674",
        "surface-tint": "#004ee8",
        "primary": "#0042c8",
        "outline-variant": "#c3c5d9",
        "secondary-container": "#e2dfde",
        "surface-bright": "#fcf9f8",
        "on-secondary": "#ffffff",
        "tertiary-container": "#007095",
        "primary-container": "#0056ff",
        "secondary-fixed-dim": "#c8c6c5",
        "surface": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "primary-fixed": "#dce1ff",
        "on-secondary-fixed-variant": "#474746",
        "tertiary-fixed": "#c2e8ff",
        "inverse-primary": "#b6c4ff",
        "tertiary-fixed-dim": "#75d1ff",
        "surface-container": "#f0edec",
        "surface-variant": "#e5e2e1",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "background": "#fcf9f8",
      },
      fontFamily: {
        "headline": ["var(--font-space-grotesk)", "sans-serif"],
        "body": ["var(--font-manrope)", "sans-serif"],
        "label": ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
